version = "3.11.5"
runner.dialect = scala3future
maxColumn = 150
newlines.source = keep
align.preset = more
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
docstrings.style = Asterisk
