rules = [
  RemoveUnused
  DisableSyntax
]

dialectOverride.allowCaptureChecking = true

DisableSyntax.noThrows = true
DisableSyntax.noNulls = true
DisableSyntax.noVars = true
DisableSyntax.noAsInstanceOf = true
DisableSyntax.noIsInstanceOf = true
DisableSyntax.noMutableCollections = true
DisableSyntax.noUniversalEquality = true
DisableSyntax.noReturns = true
DisableSyntax.noWhileLoops = true
DisableSyntax.noFinalize = true
